apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: movie-recommender
  namespace: default  # Ensure namespace is specified
spec:
  predictor:
    tensorflow:
      storageUri: "pvc://model-pvc/recommender_model"
